# Generated by Django 4.2 on 2023-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_attendance',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_attendance',
            field=models.TextField(default=False),
        ),
    ]
