# Generated by Django 4.2 on 2023-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='data',
            new_name='date',
        ),
    ]
