# Generated by Django 4.2 on 2023-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_rename_data_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='year',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
